apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://companyapp-db.postgres.database.azure.com:5432/companydb?sslmode=require
  LOG_LEVEL: DEBUG
