version: '3.9'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: companydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: companyapp-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/companydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres-data:
