# k8s/k8s-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: companyapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: companyapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: companyapp
    spec:
      containers:
        - name: companyapp
          # The image will be updated dynamically by GitHub Actions
          image: amshupatel/companyapp:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://ep-lingering-wind-a8x7ctq2-pooler.eastus2.azure.neon.tech:5432/neondb?sslmode=require&channel_binding=require"
            - name: SPRING_DATASOURCE_USERNAME
              value: "neondb_owner"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "npg_LdZr4WwpPQ7o"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
