name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Step 3: Build Maven project
      - name: Build with Maven
        run: mvn -B clean package -DskipTests
        shell: cmd

      # Step 4: Log in to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build and Push Docker image (CMD)
      - name: Build and Push Docker Image
        shell: cmd
        run: |
          set IMAGE=amshupatel/companyapp:%GITHUB_SHA%
          REM Convert IMAGE to lowercase (Windows CMD workaround)
          powershell -Command "$env:IMAGE=$env:IMAGE.ToLower(); echo 'Building image:' $env:IMAGE; docker build -t $env:IMAGE .; docker push $env:IMAGE"

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Kubernetes
        shell: cmd
        run: |
          set IMAGE=amshupatel/companyapp:%GITHUB_SHA%
          powershell -Command "$env:IMAGE=$env:IMAGE.ToLower(); kubectl apply -f k8s/k8s-deployment.yaml; kubectl set image deployment/companyapp companyapp=$env:IMAGE; kubectl rollout status deployment/companyapp --timeout=300s"
