name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        shell: cmd

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        shell: cmd
        run: |
          REM Convert Git SHA to lowercase and build Docker image
          for /f "delims=" %%i in ('powershell -Command "$env:GITHUB_SHA.ToLower()"') do set IMAGE=amshupatel/companyapp:%%i
          echo Building image %IMAGE%
          docker build -t %IMAGE% .
          docker push %IMAGE%

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Kubernetes
        shell: cmd
        run: |
          REM Use same Docker image as pushed
          for /f "delims=" %%i in ('powershell -Command "$env:GITHUB_SHA.ToLower()"') do set IMAGE=amshupatel/companyapp:%%i
          echo Deploying image %IMAGE%
          kubectl apply -f k8s/k8s-deployment.yaml
          kubectl apply -f k8s/k8s-service.yaml
          kubectl set image deployment/companyapp companyapp=%IMAGE%
          kubectl rollout status deployment/companyapp --timeout=300s
