name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Step 3: Build Maven project
      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      # Step 4: Log in to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build and Push Docker image
      - name: Build and Push Docker Image
        run: |
          IMAGE=amshupatel/companyapp:${{ github.sha }}
          echo "Building image $IMAGE"
          docker build -t $IMAGE .
          docker push $IMAGE

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        env:
          IMAGE: amshupatel/companyapp:${{ github.sha }}
        run: |
          # Apply only existing deployment YAML
          kubectl apply -f k8s/k8s-deployment.yaml

          # Update image to the new SHA
          kubectl set image deployment/companyapp companyapp=$IMAGE

          # Wait for rollout
          kubectl rollout status deployment/companyapp --timeout=300s
